version: '2.4'
services:
  metadata:
    image: postgres:11.5
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ${DB_DATA_DIR:-./db_vol}:/var/lib/postgresql/data
  
  webserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    depends_on:
      - metadata
    env_file:
      - .env
    ports:
      - "80:8080"
    volumes:
      - ${HEDWIG_DIRECTORY}:/usr/local/airflow/plugins
    healthcheck:
      test: ["CMD", "python", "/health.py"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 120s


